sonar.projectKey=shalakanaik3_aceest-fitness-devops
sonar.organization=shalakanaik3
sonar.projectName=ACEest-Fitness-Gym-DevOps
sonar.projectVersion=2.0

# Path to the source code
sonar.sources=.

# Set precise Python version to clear the warning
sonar.python.version=3.14.3
sonar.sourceEncoding=UTF-8

# Exclude test files and virtual environments from analysis
sonar.exclusions=**/tests/**, **/venv/**, **/.pytest_cache/**, aceest_fitness.db