# Unique identifier for your project in SonarCloud
sonar.projectKey=shalakanaik3_aceest-fitness-devops
sonar.organization=shalakanaik3

# This is the name displayed in the SonarCloud UI
sonar.projectName=ACEest-Fitness-Gym-DevOps
sonar.projectVersion=2.0

# Path to the source code (usually current directory)
sonar.sources=.

# Tell SonarQube to look for your Pytest results
sonar.python.version=3
sonar.language=py
sonar.sourceEncoding=UTF-8

# Exclude test files from being analyzed as source code
sonar.exclusions=**/tests/**