apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aceest-fitness
  template:
    metadata:
      labels:
        app: aceest-fitness
    spec:
      containers:
      - name: fitness-app
        image: shalaka3/aceest-fitness:1.14.2
        imagePullPolicy: Always
        env:
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"
        - name: APP_TOKEN  # Must match app.py to bypass Sonar scan
          valueFrom:
            secretKeyRef:
              name: fitness-secrets
              key: flask-secret
        - name: username
          value: "fitness_admin"
        - name: password
          valueFrom:
            secretKeyRef:
              name: fitness-secrets
              key: db-password
        resources:
          requests:
            cpu: 0.5
            memory: 100Mi
            # SONAR FIX: Added storage request.
            ephemeral-storage: "2Gi"
          limits:
            memory: 100Mi
        ports:
        - containerPort: 5000
      automountServiceAccountToken: false