apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-deployment
spec:
  replicas: 3 
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: aceest-fitness
  template:
    metadata:
      labels:
        app: aceest-fitness
    spec:
      containers:
      - name: fitness-app
        image: shalaka3/aceest-fitness:1.14.2 
        env:
        # Injected from a K8s Secret to satisfy security requirements
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: fitness-secrets
              key: flask-secret
        # Adding the variables referenced in your app.py
        - name: username
          value: "admin_user"
        - name: password
          valueFrom:
            secretKeyRef:
              name: fitness-secrets
              key: db-password
        resources:
          limits:
            memory: 100Mi
          requests:
            ephemeral-storage: "2Gi"
            cpu: 0.5
            memory: 100Mi
        ports:
        - containerPort: 5000
      automountServiceAccountToken: false